controller:
  extraArgs:
  - --application-namespaces="*"
  replicas: 1

server:
  extraArgs:
  - --application-namespaces="*"
  autoscaling:
    enabled: true
    minReplicas: 2

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

applicationSet:
  replicas: 2

configs:
  params:
    server.insecure: true
