prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: prometheus-data
        spec:
          storageClassName: "nfs-storage"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi

grafana:
  initChownData:
    enabled: false
  persistence:
    enabled: true
    storageClassName: "nfs-storage"
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 20Gi

prometheusOperator:
  tls:
    enabled: false
  admissionWebhooks:
    enabled: false
